const compoundsData = [
    {
        "id": "1",
        "name": "Protocatechuic acid",
        "class": "Hydroxybenzoic acids",
        "molecular_formula": "C7H6O4",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9911",
        "smiles": "C1=CC(=C(C=C1C(=O)O)O)O",
        "image": "mol_1.svg",
        "sdf": "mol_1.sdf",
        "mw": 154.03,
        "logp": 0.8,
        "tpsa": 77.76,
        "hbd": 3,
        "hba": 3,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "Phenolic acids distributed across leaves and stems of C. majus aerial parts"
    },
    {
        "id": "2",
        "name": "Veratric Acid",
        "class": "Hydroxybenzoic acids",
        "molecular_formula": "C9H10O4",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9912",
        "smiles": "COC1=C(C=C(C=C1)C(=O)O)OC",
        "image": "mol_2.svg",
        "sdf": "mol_2.sdf",
        "mw": 182.06,
        "logp": 1.4,
        "tpsa": 55.76,
        "hbd": 1,
        "hba": 3,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "Phenolic acids distributed across leaves and stems of C. majus aerial parts"
    },
    {
        "id": "3",
        "name": "Salicylic acid",
        "class": "Hydroxybenzoic acids",
        "molecular_formula": "C7H6O3",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9913",
        "smiles": "C1=CC=C(C(=C1)C(=O)O)O",
        "image": "mol_3.svg",
        "sdf": "mol_3.sdf",
        "mw": 138.03,
        "logp": 1.09,
        "tpsa": 57.53,
        "hbd": 2,
        "hba": 2,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "Identified in aerial parts extract; salicylic acid abundant (123.6 \u00b5g/g) in C. majus"
    },
    {
        "id": "4",
        "name": "4-H-phenylacetic acid",
        "class": "Hydroxybenzoic acids",
        "molecular_formula": "C8H8O3",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9914",
        "smiles": "COC(=O)C1=CC=C(C=C1)O",
        "image": "mol_4.svg",
        "sdf": "mol_4.sdf",
        "mw": 152.05,
        "logp": 1.18,
        "tpsa": 46.53,
        "hbd": 1,
        "hba": 3,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "Phenolic acids distributed across leaves and stems of C. majus aerial parts"
    },
    {
        "id": "5",
        "name": "Vanillic acid",
        "class": "Hydroxybenzoic acids",
        "molecular_formula": "C8H8O4",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9915",
        "smiles": "COC1=C(C=CC(=C1)C(=O)O)O",
        "image": "mol_5.svg",
        "sdf": "mol_5.sdf",
        "mw": 168.04,
        "logp": 1.1,
        "tpsa": 66.76,
        "hbd": 2,
        "hba": 3,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "Phenolic acids distributed across leaves and stems of C. majus aerial parts"
    },
    {
        "id": "6",
        "name": "Ellagic Acid",
        "class": "Hydroxybenzoic acids",
        "molecular_formula": "C14H6O8",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9916",
        "smiles": "C1=C2C3=C(C(=C1O)O)OC(=O)C4=CC(=C(C(=C43)OC2=O)O)O",
        "image": "mol_6.svg",
        "sdf": "mol_6.sdf",
        "mw": 302.01,
        "logp": 1.31,
        "tpsa": 141.34,
        "hbd": 4,
        "hba": 8,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "Ellagic acid identified from aerial parts of C. majus"
    },
    {
        "id": "7",
        "name": "Dihydrocaffeic acid",
        "class": "Hydroxycinnamic acids",
        "molecular_formula": "C9H10O4",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9917",
        "smiles": "C1=CC(=C(C=C1CCC(=O)O)O)O",
        "image": "mol_7.svg",
        "sdf": "mol_7.sdf",
        "mw": 182.06,
        "logp": 1.11,
        "tpsa": 77.76,
        "hbd": 3,
        "hba": 3,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "Hydroxycinnamic acids identified from aerial parts (Borges et al., 2025)"
    },
    {
        "id": "8",
        "name": "Neochlorogenic acid",
        "class": "Hydroxycinnamic acids",
        "molecular_formula": "C16H18O9",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9918",
        "smiles": "C1[C@H]([C@@H]([C@@H](C[C@]1(C(=O)O)O)OC(=O)/C=C/C2=CC(=C(C=C2)O)O)O)O",
        "image": "mol_8.svg",
        "sdf": "mol_8.sdf",
        "mw": 354.1,
        "logp": -0.65,
        "tpsa": 164.75,
        "hbd": 6,
        "hba": 8,
        "lipinski_pass": true,
        "ro5_violations": 1,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "Neochlorogenic acid from aerial parts of C. majus"
    },
    {
        "id": "9",
        "name": "Caffeic acid",
        "class": "Hydroxycinnamic acids",
        "molecular_formula": "C9H8O4",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9919",
        "smiles": "C1=CC(=C(C=C1/C=C/C(=O)O)O)O",
        "image": "mol_9.svg",
        "sdf": "mol_9.sdf",
        "mw": 180.04,
        "logp": 1.2,
        "tpsa": 77.76,
        "hbd": 3,
        "hba": 3,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "Caffeic acid (0.4%) reported in aerial parts (EMA monograph)"
    },
    {
        "id": "10",
        "name": "Homovanillic acid",
        "class": "Hydroxycinnamic acids",
        "molecular_formula": "C9H10O4",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9920",
        "smiles": "COC1=C(C=CC(=C1)CC(=O)O)O",
        "image": "mol_10.svg",
        "sdf": "mol_10.sdf",
        "mw": 182.06,
        "logp": 1.03,
        "tpsa": 66.76,
        "hbd": 2,
        "hba": 3,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "Homovanillic acid from aerial parts of C. majus"
    },
    {
        "id": "11",
        "name": "p-Coumaric acid",
        "class": "Hydroxycinnamic acids",
        "molecular_formula": "C9H8O3",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9921",
        "smiles": "C1=CC(=CC=C1/C=C/C(=O)O)O",
        "image": "mol_11.svg",
        "sdf": "mol_11.sdf",
        "mw": 164.05,
        "logp": 1.49,
        "tpsa": 57.53,
        "hbd": 2,
        "hba": 2,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "p-Coumaric acid (0.06%) in aerial parts (EMA monograph)"
    },
    {
        "id": "12",
        "name": "Ferulic acid",
        "class": "Hydroxycinnamic acids",
        "molecular_formula": "C10H10O4",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9922",
        "smiles": "COC1=C(C=CC(=C1)/C=C/C(=O)O)O",
        "image": "mol_12.svg",
        "sdf": "mol_12.sdf",
        "mw": 194.06,
        "logp": 1.5,
        "tpsa": 66.76,
        "hbd": 2,
        "hba": 3,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "Ferulic acid (0.02%) in aerial parts (EMA monograph)"
    },
    {
        "id": "13",
        "name": "4,5-Dicaffeoylquinic acid",
        "class": "Hydroxycinnamic acids",
        "molecular_formula": "C25H24O12",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9923",
        "smiles": "C1[C@H]([C@H]([C@@H](C[C@@]1(C(=O)O)O)OC(=O)/C=C/C2=CC(=C(C=C2)O)O)OC(=O)/C=C/C3=CC(=C(C=C3)O)O)O",
        "image": "mol_13.svg",
        "sdf": "mol_13.sdf",
        "mw": 516.13,
        "logp": 1.03,
        "tpsa": 211.28,
        "hbd": 7,
        "hba": 11,
        "lipinski_pass": false,
        "ro5_violations": 3,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "4,5-Dicaffeoylquinic acid from aerial parts; identified in C. majus extract (Borges et al., 2025)"
    },
    {
        "id": "14",
        "name": "Feruloylagmatine",
        "class": "Hydroxycinnamic acid amides",
        "molecular_formula": "C15H22N4O3",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9924",
        "smiles": "COC1=C(C=CC(=C1)/C=C/C(=O)NCCCCN=C(N)N)O",
        "image": "mol_14.svg",
        "sdf": "mol_14.sdf",
        "mw": 306.17,
        "logp": 0.58,
        "tpsa": 122.96,
        "hbd": 4,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (stems, seeds)",
        "literature_note": "Feruloylagmatine from aerial parts of C. majus"
    },
    {
        "id": "15",
        "name": "p-Coumaroylputrescine",
        "class": "Hydroxycinnamic acid amides",
        "molecular_formula": "C13H18N2O2",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9925",
        "smiles": "C1=CC(=CC=C1/C=C/C(=O)NCCCCN)O",
        "image": "mol_15.svg",
        "sdf": "mol_15.sdf",
        "mw": 234.14,
        "logp": 1.26,
        "tpsa": 75.35,
        "hbd": 3,
        "hba": 3,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (stems, seeds)",
        "literature_note": "p-Coumaroylputrescine identified in aerial parts"
    },
    {
        "id": "16",
        "name": "N-Caffeoyltyramine",
        "class": "Hydroxycinnamic acid amides",
        "molecular_formula": "C17H17NO4",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9926",
        "smiles": "C1=CC(=CC=C1CCNC(=O)/C=C/C2=CC(=C(C=C2)O)O)O",
        "image": "mol_16.svg",
        "sdf": "mol_16.sdf",
        "mw": 299.12,
        "logp": 2.18,
        "tpsa": 89.79,
        "hbd": 4,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (stems, seeds)",
        "literature_note": "N-Caffeoyltyramine from aerial parts of C. majus"
    },
    {
        "id": "17",
        "name": "p-Coumaroyltyramine",
        "class": "Hydroxycinnamic acid amides",
        "molecular_formula": "C17H17NO3",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9927",
        "smiles": "C1=CC(=CC=C1CCNC(=O)/C=C/C2=CC=C(C=C2)O)O",
        "image": "mol_17.svg",
        "sdf": "mol_17.sdf",
        "mw": 283.12,
        "logp": 2.47,
        "tpsa": 69.56,
        "hbd": 3,
        "hba": 3,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (stems, seeds)",
        "literature_note": "p-Coumaroyltyramine abundant (111.8 \u00b5g/g) in C. majus aerial parts (Borges et al., 2025)"
    },
    {
        "id": "18",
        "name": "Feruloyltyramine",
        "class": "Hydroxycinnamic acid amides",
        "molecular_formula": "C18H19O4N",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9928",
        "smiles": "COC1=C(C=CC(=C1)/C=C/C(=O)NCCC2=CC=C(C=C2)O)O",
        "image": "mol_18.svg",
        "sdf": "mol_18.sdf",
        "mw": 313.13,
        "logp": 2.48,
        "tpsa": 78.79,
        "hbd": 3,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (stems, seeds)",
        "literature_note": "Feruloyltyramine from aerial parts of C. majus"
    },
    {
        "id": "19",
        "name": "p-Coumaroyltryptamine",
        "class": "Hydroxycinnamic acid amides",
        "molecular_formula": "C19H18N2O2",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9929",
        "smiles": "C1=CC=C2C(=C1)C(=CN2)CCNC(=O)/C=C/C3=CC=C(C=C3)O",
        "image": "mol_19.svg",
        "sdf": "mol_19.sdf",
        "mw": 306.14,
        "logp": 3.25,
        "tpsa": 65.12,
        "hbd": 3,
        "hba": 2,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (stems, seeds)",
        "literature_note": "p-Coumaroyltryptamine from aerial parts of C. majus"
    },
    {
        "id": "20",
        "name": "Catechin",
        "class": "Flavanol",
        "molecular_formula": "C15H14O6",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9930",
        "smiles": "C1[C@@H]([C@H](OC2=CC(=CC(=C21)O)O)C3=CC(=C(C=C3)O)O)O",
        "image": "mol_20.svg",
        "sdf": "mol_20.sdf",
        "mw": 290.08,
        "logp": 1.55,
        "tpsa": 110.38,
        "hbd": 5,
        "hba": 6,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, flowers)",
        "literature_note": "Catechin identified in aerial parts; leaves show highest flavonoid content"
    },
    {
        "id": "21",
        "name": "Epicatechin",
        "class": "Flavanol",
        "molecular_formula": "C15H14O6",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9931",
        "smiles": "C1[C@H]([C@H](OC2=CC(=CC(=C21)O)O)C3=CC(=C(C=C3)O)O)O",
        "image": "mol_21.svg",
        "sdf": "mol_21.sdf",
        "mw": 290.08,
        "logp": 1.55,
        "tpsa": 110.38,
        "hbd": 5,
        "hba": 6,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, flowers)",
        "literature_note": "Epicatechin from aerial parts of C. majus; leaves/flowers"
    },
    {
        "id": "22",
        "name": "Hesperidin",
        "class": "Flavanone",
        "molecular_formula": "C28H34O15",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9932",
        "smiles": "C[C@H]1[C@@H]([C@H]([C@H]([C@@H](O1)OC[C@@H]2[C@H]([C@@H]([C@H]([C@@H](O2)OC3=CC(=C4C(=O)C[C@H](OC4=C3)C5=CC(=C(C=C5)OC)O)O)O)O)O)O)O)O",
        "image": "mol_22.svg",
        "sdf": "mol_22.sdf",
        "mw": 610.19,
        "logp": -1.16,
        "tpsa": 234.29,
        "hbd": 8,
        "hba": 15,
        "lipinski_pass": false,
        "ro5_violations": 3,
        "plant_part": "Aerial parts (leaves, flowers)",
        "literature_note": "Hesperidin identified in C. majus aerial parts (Borges et al., 2025)"
    },
    {
        "id": "23",
        "name": "Naringenin",
        "class": "Flavanone",
        "molecular_formula": "C15H12O5",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9933",
        "smiles": "C1[C@H](OC2=CC(=CC(=C2C1=O)O)O)C3=CC=C(C=C3)O",
        "image": "mol_23.svg",
        "sdf": "mol_23.sdf",
        "mw": 272.07,
        "logp": 2.51,
        "tpsa": 86.99,
        "hbd": 3,
        "hba": 5,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, flowers)",
        "literature_note": "Naringenin from aerial parts of C. majus"
    },
    {
        "id": "24",
        "name": "Hesperetin",
        "class": "Flavanone",
        "molecular_formula": "C16H14O6",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9934",
        "smiles": "COC1=C(C=C(C=C1)[C@@H]2CC(=O)C3=C(C=C(C=C3O2)O)O)O",
        "image": "mol_24.svg",
        "sdf": "mol_24.sdf",
        "mw": 302.08,
        "logp": 2.52,
        "tpsa": 96.22,
        "hbd": 3,
        "hba": 6,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, flowers)",
        "literature_note": "Hesperetin from aerial parts of C. majus"
    },
    {
        "id": "25",
        "name": "Pinocembrin",
        "class": "Flavanone",
        "molecular_formula": "C15H12O4",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9935",
        "smiles": "C1[C@H](OC2=CC(=CC(=C2C1=O)O)O)C3=CC=CC=C3",
        "image": "mol_25.svg",
        "sdf": "mol_25.sdf",
        "mw": 256.07,
        "logp": 2.8,
        "tpsa": 66.76,
        "hbd": 2,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, flowers)",
        "literature_note": "Pinocembrin abundant (98.4 \u00b5g/g) in C. majus aerial parts (Borges et al., 2025)"
    },
    {
        "id": "26",
        "name": "Vitexin",
        "class": "Flavone",
        "molecular_formula": "C21H20O10",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9936",
        "smiles": "C1=CC(=CC=C1C2=CC(=O)C3=C(O2)C(=C(C=C3O)O)[C@H]4[C@@H]([C@H]([C@@H]([C@H](O4)CO)O)O)O)O",
        "image": "mol_26.svg",
        "sdf": "mol_26.sdf",
        "mw": 432.11,
        "logp": 0.09,
        "tpsa": 181.05,
        "hbd": 7,
        "hba": 10,
        "lipinski_pass": true,
        "ro5_violations": 1,
        "plant_part": "Aerial parts (leaves, flowers)",
        "literature_note": "Vitexin from aerial parts of C. majus (Borges et al., 2025)"
    },
    {
        "id": "27",
        "name": "Cynaroside",
        "class": "Flavone",
        "molecular_formula": "C21H20O11",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9937",
        "smiles": "C1=CC(=C(C=C1C2=CC(=O)C3=C(C=C(C=C3O2)O[C@H]4[C@@H]([C@H]([C@@H]([C@H](O4)CO)O)O)O)O)O)O",
        "image": "mol_27.svg",
        "sdf": "mol_27.sdf",
        "mw": 448.1,
        "logp": -0.24,
        "tpsa": 190.28,
        "hbd": 7,
        "hba": 11,
        "lipinski_pass": false,
        "ro5_violations": 2,
        "plant_part": "Aerial parts (leaves, flowers)",
        "literature_note": "Cynaroside (luteolin-7-glucoside) from aerial parts"
    },
    {
        "id": "28",
        "name": "Diosmin",
        "class": "Flavone",
        "molecular_formula": "C28H32O15",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9938",
        "smiles": "C[C@H]1[C@@H]([C@H]([C@H]([C@@H](O1)OC[C@@H]2[C@H]([C@@H]([C@H]([C@@H](O2)OC3=CC(=C4C(=C3)OC(=CC4=O)C5=CC(=C(C=C5)OC)O)O)O)O)O)O)O)O",
        "image": "mol_28.svg",
        "sdf": "mol_28.sdf",
        "mw": 608.17,
        "logp": -1.09,
        "tpsa": 238.2,
        "hbd": 8,
        "hba": 15,
        "lipinski_pass": false,
        "ro5_violations": 3,
        "plant_part": "Aerial parts (leaves, flowers)",
        "literature_note": "Diosmin identified in C. majus aerial parts"
    },
    {
        "id": "29",
        "name": "Apigetrin",
        "class": "Flavone",
        "molecular_formula": "C21H20O10",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9939",
        "smiles": "C1=CC(=CC=C1C2=CC(=O)C3=C(C=C(C=C3O2)O[C@H]4[C@@H]([C@H]([C@@H]([C@H](O4)CO)O)O)O)O)O",
        "image": "mol_29.svg",
        "sdf": "mol_29.sdf",
        "mw": 432.11,
        "logp": 0.05,
        "tpsa": 170.05,
        "hbd": 6,
        "hba": 10,
        "lipinski_pass": true,
        "ro5_violations": 1,
        "plant_part": "Aerial parts (leaves, flowers)",
        "literature_note": "Apigetrin from aerial parts of C. majus"
    },
    {
        "id": "30",
        "name": "Diosmetin-7-glucoside",
        "class": "Flavone",
        "molecular_formula": "C22H22O11",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9940",
        "smiles": "COC1=C(C=C(C=C1)C2=CC(=O)C3=C(C=C(C=C3O2)O[C@H]4[C@@H]([C@H]([C@@H]([C@H](O4)CO)O)O)O)O)O",
        "image": "mol_30.svg",
        "sdf": "mol_30.sdf",
        "mw": 462.12,
        "logp": 0.06,
        "tpsa": 179.28,
        "hbd": 6,
        "hba": 11,
        "lipinski_pass": false,
        "ro5_violations": 2,
        "plant_part": "Aerial parts (leaves, flowers)",
        "literature_note": "Diosmetin-7-glucoside from aerial parts of C. majus"
    },
    {
        "id": "31",
        "name": "Luteolin/Scutellarein",
        "class": "Flavone",
        "molecular_formula": "C15H10O6",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9941",
        "smiles": "C1=CC(=C(C=C1C2=CC(=O)C3=C(C=C(C=C3O2)O)O)O)O",
        "image": "mol_31.svg",
        "sdf": "mol_31.sdf",
        "mw": 286.05,
        "logp": 2.28,
        "tpsa": 111.13,
        "hbd": 4,
        "hba": 6,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, flowers)",
        "literature_note": "Luteolin/Scutellarein from aerial parts of C. majus"
    },
    {
        "id": "32",
        "name": "Apigenin",
        "class": "Flavone",
        "molecular_formula": "C15H10O5",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9942",
        "smiles": "C1=CC(=CC=C1C2=CC(=O)C3=C(C=C(C=C3O2)O)O)O",
        "image": "mol_32.svg",
        "sdf": "mol_32.sdf",
        "mw": 270.05,
        "logp": 2.58,
        "tpsa": 90.9,
        "hbd": 3,
        "hba": 5,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, flowers)",
        "literature_note": "Apigenin from aerial parts of C. majus"
    },
    {
        "id": "33",
        "name": "Diosmetin",
        "class": "Flavone",
        "molecular_formula": "C16H12O6",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9943",
        "smiles": "COC1=C(C=C(C=C1)C2=CC(=O)C3=C(C=C(C=C3O2)O)O)O",
        "image": "mol_33.svg",
        "sdf": "mol_33.sdf",
        "mw": 300.06,
        "logp": 2.59,
        "tpsa": 100.13,
        "hbd": 3,
        "hba": 6,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, flowers)",
        "literature_note": "Diosmetin from aerial parts of C. majus"
    },
    {
        "id": "34",
        "name": "Isorhamnetin-rutinoside- glucoside",
        "class": "Flavonol",
        "molecular_formula": "C34H42O21",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9944",
        "smiles": "C[C@H]1[C@@H]([C@H]([C@H]([C@@H](O1)OC[C@@H]2[C@H]([C@@H]([C@H]([C@@H](O2)OC3=C(OC4=CC(=CC(=C4C3=O)O)O[C@H]5[C@@H]([C@H]([C@@H]([C@H](O5)CO)O)O)O)C6=CC(=C(C=C6)O)OC)O)O)O)O)O)O",
        "image": "mol_34.svg",
        "sdf": "mol_34.sdf",
        "mw": 786.22,
        "logp": -3.91,
        "tpsa": 337.58,
        "hbd": 12,
        "hba": 21,
        "lipinski_pass": false,
        "ro5_violations": 3,
        "plant_part": "Aerial parts (leaves)",
        "literature_note": "Isorhamnetin-rutinoside-glucoside from leaves of C. majus; leaves have highest flavonoid content"
    },
    {
        "id": "35",
        "name": "Quercetin-3-rhamnosylrutinoside",
        "class": "Flavonol",
        "molecular_formula": "C33H40O20",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9945",
        "smiles": "C[C@H]1[C@@H]([C@H]([C@H]([C@@H](O1)OC2=CC(=C3C(=C2)OC(=C(C3=O)O[C@H]4[C@@H]([C@H]([C@@H]([C@H](O4)CO[C@H]5[C@@H]([C@H]([C@@H]([C@H](O5)CO)O)O)O)O)O)O)C6=CC=C(C=C6)O)O)O)O)O",
        "image": "mol_35.svg",
        "sdf": "mol_35.sdf",
        "mw": 756.21,
        "logp": -3.92,
        "tpsa": 328.35,
        "hbd": 12,
        "hba": 20,
        "lipinski_pass": false,
        "ro5_violations": 3,
        "plant_part": "Aerial parts (leaves)",
        "literature_note": "Quercetin-3-rhamnosylrutinoside from aerial parts (Borges et al., 2025)"
    },
    {
        "id": "36",
        "name": "Isorhamnetin rutinoside-rhamnoside",
        "class": "Flavonol",
        "molecular_formula": "C34H42O20",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9946",
        "smiles": "C[C@H]1[C@@H]([C@H]([C@H]([C@@H](O1)OC[C@@H]2[C@H]([C@@H]([C@H]([C@@H](O2)OC3=C(OC4=CC(=CC(=C4C3=O)O)O)C5=CC=C(C=C5)OC)O[C@H]6[C@@H]([C@H]([C@@H]([C@H](O6)CO)O)O)O)O)O)O)O)O",
        "image": "mol_36.svg",
        "sdf": "mol_36.sdf",
        "mw": 770.23,
        "logp": -3.27,
        "tpsa": 317.35,
        "hbd": 11,
        "hba": 20,
        "lipinski_pass": false,
        "ro5_violations": 3,
        "plant_part": "Aerial parts (leaves)",
        "literature_note": "Isorhamnetin rutinoside-rhamnoside from aerial parts of C. majus"
    },
    {
        "id": "37",
        "name": "Rutin",
        "class": "Flavonol",
        "molecular_formula": "C27H30O16",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9947",
        "smiles": "C[C@H]1[C@@H]([C@H]([C@H]([C@@H](O1)OC[C@@H]2[C@H]([C@@H]([C@H]([C@@H](O2)OC3=C(OC4=CC(=CC(=C4C3=O)O)O)C5=CC(=C(C=C5)O)O)O)O)O)O)O)O",
        "image": "mol_37.svg",
        "sdf": "mol_37.sdf",
        "mw": 610.15,
        "logp": -1.69,
        "tpsa": 269.43,
        "hbd": 10,
        "hba": 16,
        "lipinski_pass": false,
        "ro5_violations": 3,
        "plant_part": "Aerial parts (leaves)",
        "literature_note": "Rutin (quercetin-3-rutinoside) reported in aerial parts of C. majus"
    },
    {
        "id": "38",
        "name": "Quercetin-glucoside",
        "class": "Flavonol",
        "molecular_formula": "C21H20O12",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9948",
        "smiles": "C1=CC(=C(C=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O[C@H]4[C@@H]([C@H]([C@@H]([C@H](O4)CO)O)O)O)O)O",
        "image": "mol_38.svg",
        "sdf": "mol_38.sdf",
        "mw": 464.1,
        "logp": -0.54,
        "tpsa": 210.51,
        "hbd": 8,
        "hba": 12,
        "lipinski_pass": false,
        "ro5_violations": 2,
        "plant_part": "Aerial parts (leaves)",
        "literature_note": "Quercetin-glucoside from aerial parts of C. majus"
    },
    {
        "id": "39",
        "name": "Kaempferol 3-rutinoside",
        "class": "Flavonol",
        "molecular_formula": "C27H30O15",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9949",
        "smiles": "C[C@H]1[C@@H]([C@H]([C@H]([C@@H](O1)OC[C@@H]2[C@H]([C@@H]([C@H]([C@@H](O2)OC3=C(OC4=CC(=CC(=C4C3=O)O)O)C5=CC=C(C=C5)O)O)O)O)O)O)O",
        "image": "mol_39.svg",
        "sdf": "mol_39.sdf",
        "mw": 594.16,
        "logp": -1.39,
        "tpsa": 249.2,
        "hbd": 9,
        "hba": 15,
        "lipinski_pass": false,
        "ro5_violations": 3,
        "plant_part": "Aerial parts (leaves)",
        "literature_note": "Kaempferol 3-rutinoside from aerial parts of C. majus (Borges et al., 2025)"
    },
    {
        "id": "40",
        "name": "Isorhamnetin rutinoside",
        "class": "Flavonol",
        "molecular_formula": "C28H32O16",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9950",
        "smiles": "C[C@H]1[C@@H]([C@H]([C@H]([C@@H](O1)OCC2[C@H]([C@@H]([C@H]([C@@H](O2)OC3=C(OC4=CC(=CC(=C4C3=O)O)O)C5=CC(=C(C=C5)O)OC)O)O)O)O)O)O",
        "image": "mol_40.svg",
        "sdf": "mol_40.sdf",
        "mw": 624.17,
        "logp": -1.38,
        "tpsa": 258.43,
        "hbd": 9,
        "hba": 16,
        "lipinski_pass": false,
        "ro5_violations": 3,
        "plant_part": "Aerial parts (leaves)",
        "literature_note": "Isorhamnetin rutinoside from aerial parts of C. majus"
    },
    {
        "id": "41",
        "name": "Guaiaverin/Reynoutrin",
        "class": "Flavonol",
        "molecular_formula": "C20H18O11",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9951",
        "smiles": "C1=CC(=C(C=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O[C@H]4[C@@H]([C@H]([C@@H](O4)CO)O)O)O)O",
        "image": "mol_41.svg",
        "sdf": "mol_41.sdf",
        "mw": 434.08,
        "logp": 0.1,
        "tpsa": 190.28,
        "hbd": 7,
        "hba": 11,
        "lipinski_pass": false,
        "ro5_violations": 2,
        "plant_part": "Aerial parts (leaves)",
        "literature_note": "Guaiaverin/Reynoutrin from aerial parts of C. majus"
    },
    {
        "id": "42",
        "name": "Quercitrin/Quercetin 3-rhamnoside",
        "class": "Flavonol",
        "molecular_formula": "C21H20O11",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9952",
        "smiles": "C[C@H]1[C@@H]([C@H]([C@H]([C@@H](O1)OC2=C(OC3=CC(=CC(=C3C2=O)O)O)C4=CC(=C(C=C4)O)O)O)O)O",
        "image": "mol_42.svg",
        "sdf": "mol_42.sdf",
        "mw": 448.1,
        "logp": 0.49,
        "tpsa": 190.28,
        "hbd": 7,
        "hba": 11,
        "lipinski_pass": false,
        "ro5_violations": 2,
        "plant_part": "Aerial parts (leaves)",
        "literature_note": "Quercitrin/Quercetin 3-rhamnoside from aerial parts of C. majus"
    },
    {
        "id": "43",
        "name": "Isorhamnetin-3-glucoside",
        "class": "Flavonol",
        "molecular_formula": "C22H22O12",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9953",
        "smiles": "COC1=C(C=CC(=C1)C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O[C@H]4[C@@H]([C@H]([C@@H]([C@H](O4)CO)O)O)O)O",
        "image": "mol_43.svg",
        "sdf": "mol_43.sdf",
        "mw": 478.11,
        "logp": -0.24,
        "tpsa": 199.51,
        "hbd": 7,
        "hba": 12,
        "lipinski_pass": false,
        "ro5_violations": 2,
        "plant_part": "Aerial parts (leaves)",
        "literature_note": "Isorhamnetin-3-glucoside from aerial parts of C. majus"
    },
    {
        "id": "44",
        "name": "Quercetin",
        "class": "Flavonol",
        "molecular_formula": "C15H10O7",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9954",
        "smiles": "C1=CC(=C(C=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O)O)O",
        "image": "mol_44.svg",
        "sdf": "mol_44.sdf",
        "mw": 302.04,
        "logp": 1.99,
        "tpsa": 131.36,
        "hbd": 5,
        "hba": 7,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves)",
        "literature_note": "Quercetin identified in aerial parts; widely reported in C. majus"
    },
    {
        "id": "45",
        "name": "Kaempferol",
        "class": "Flavonol",
        "molecular_formula": "C15H10O6",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9955",
        "smiles": "C1=CC(=CC=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O)O",
        "image": "mol_45.svg",
        "sdf": "mol_45.sdf",
        "mw": 286.05,
        "logp": 2.28,
        "tpsa": 111.13,
        "hbd": 4,
        "hba": 6,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves)",
        "literature_note": "Kaempferol from aerial parts; identified in C. majus aerial parts"
    },
    {
        "id": "46",
        "name": "Isorhamnetin",
        "class": "Flavonol",
        "molecular_formula": "C16H12O7",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9956",
        "smiles": "COC1=C(C=CC(=C1)C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O)O",
        "image": "mol_46.svg",
        "sdf": "mol_46.sdf",
        "mw": 316.06,
        "logp": 2.29,
        "tpsa": 120.36,
        "hbd": 4,
        "hba": 7,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves)",
        "literature_note": "Isorhamnetin from aerial parts of C. majus"
    },
    {
        "id": "47",
        "name": "Esculetin/Aesculetin",
        "class": "Coumarins",
        "molecular_formula": "C9H6O4",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9957",
        "smiles": "C1=CC(=O)OC2=CC(=C(C=C21)O)O",
        "image": "mol_47.svg",
        "sdf": "mol_47.sdf",
        "mw": 178.03,
        "logp": 1.2,
        "tpsa": 70.67,
        "hbd": 2,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "Esculetin/Aesculetin from aerial parts of C. majus"
    },
    {
        "id": "48",
        "name": "Umbelliferone",
        "class": "Coumarins",
        "molecular_formula": "C9H6O3",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9958",
        "smiles": "C1=CC(=CC2=C1C=CC(=O)O2)O",
        "image": "mol_48.svg",
        "sdf": "mol_48.sdf",
        "mw": 162.03,
        "logp": 1.5,
        "tpsa": 50.44,
        "hbd": 1,
        "hba": 3,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "Umbelliferone from aerial parts of C. majus"
    },
    {
        "id": "49",
        "name": "Scoparone",
        "class": "Coumarins",
        "molecular_formula": "C11H10O4",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9959",
        "smiles": "COC1=C(C=C2C(=C1)C=CC(=O)O2)OC",
        "image": "mol_49.svg",
        "sdf": "mol_49.sdf",
        "mw": 206.06,
        "logp": 1.81,
        "tpsa": 48.67,
        "hbd": 0,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "Scoparone from aerial parts of C. majus"
    },
    {
        "id": "50",
        "name": "Scopoletin",
        "class": "Coumarins",
        "molecular_formula": "C10H8O4",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9960",
        "smiles": "COC1=C(C=C2C(=C1)C=CC(=O)O2)O",
        "image": "mol_50.svg",
        "sdf": "mol_50.sdf",
        "mw": 192.04,
        "logp": 1.51,
        "tpsa": 59.67,
        "hbd": 1,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves, stems)",
        "literature_note": "Scopoletin from aerial parts of C. majus"
    },
    {
        "id": "51",
        "name": "Resveratrol",
        "class": "Stilbenes",
        "molecular_formula": "C14H12O3",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9961",
        "smiles": "C1=CC(=CC=C1/C=C/C2=CC(=CC(=C2)O)O)O",
        "image": "mol_51.svg",
        "sdf": "mol_51.sdf",
        "mw": 228.08,
        "logp": 2.97,
        "tpsa": 60.69,
        "hbd": 3,
        "hba": 3,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts",
        "literature_note": "Resveratrol identified in C. majus aerial parts (Borges et al., 2025)"
    },
    {
        "id": "52",
        "name": "Piceatannol",
        "class": "Stilbenes",
        "molecular_formula": "C14H12O4",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9962",
        "smiles": "C1=CC(=C(C=C1/C=C/C2=CC(=CC(=C2)O)O)O)O",
        "image": "mol_52.svg",
        "sdf": "mol_52.sdf",
        "mw": 244.07,
        "logp": 2.68,
        "tpsa": 80.92,
        "hbd": 4,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts",
        "literature_note": "Piceatannol from aerial parts of C. majus"
    },
    {
        "id": "53",
        "name": "Syringaldehyde",
        "class": "Phenolic Aldehyde",
        "molecular_formula": "C9H10O4",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9963",
        "smiles": "COC1=CC(=CC(=C1O)OC)C=O",
        "image": "mol_53.svg",
        "sdf": "mol_53.sdf",
        "mw": 182.06,
        "logp": 1.22,
        "tpsa": 55.76,
        "hbd": 1,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts",
        "literature_note": "Syringaldehyde from aerial parts of C. majus"
    },
    {
        "id": "54",
        "name": "Vanillin",
        "class": "Phenolic Aldehyde",
        "molecular_formula": "C8H8O3",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9964",
        "smiles": "COC1=C(C=CC(=C1)C=O)O",
        "image": "mol_54.svg",
        "sdf": "mol_54.sdf",
        "mw": 152.05,
        "logp": 1.21,
        "tpsa": 46.53,
        "hbd": 1,
        "hba": 3,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts",
        "literature_note": "Vanillin from aerial parts of C. majus"
    },
    {
        "id": "55",
        "name": "Protocatechualdehyde",
        "class": "Phenolic Aldehyde",
        "molecular_formula": "C7H6O3",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9965",
        "smiles": "C1=CC(=C(C=C1C=O)O)O",
        "image": "mol_55.svg",
        "sdf": "mol_55.sdf",
        "mw": 138.03,
        "logp": 0.91,
        "tpsa": 57.53,
        "hbd": 2,
        "hba": 3,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts",
        "literature_note": "Protocatechualdehyde from aerial parts of C. majus"
    },
    {
        "id": "56",
        "name": "Hydrotyrosol",
        "class": "Phenylethanoids",
        "molecular_formula": "C8H8O3",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9966",
        "smiles": "COC(=O)C1=CC=C(C=C1)O",
        "image": "mol_56.svg",
        "sdf": "mol_56.sdf",
        "mw": 152.05,
        "logp": 1.18,
        "tpsa": 46.53,
        "hbd": 1,
        "hba": 3,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts",
        "literature_note": "Hydrotyrosol from aerial parts of C. majus"
    },
    {
        "id": "57",
        "name": "Phenylacetic acid",
        "class": "Phenylpropanoids",
        "molecular_formula": "C8H8O2",
        "referencias": " https://www.mdpi.com/1422-0067/26/20/9967",
        "smiles": "C1=CC=C(C=C1)CC(=O)O",
        "image": "mol_57.svg",
        "sdf": "mol_57.sdf",
        "mw": 136.05,
        "logp": 1.31,
        "tpsa": 37.3,
        "hbd": 1,
        "hba": 1,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts",
        "literature_note": "Phenylacetic acid from aerial parts of C. majus"
    },
    {
        "id": "58",
        "name": "Sanguinarine",
        "class": "Benzophenanthrine quaternary amine",
        "molecular_formula": "C20H13NO4",
        "referencias": "DOI 10.3389/fphar.2024.1440979",
        "smiles": "C[N+]1=C2C(=C3C=CC4=C(C3=C1)OCO4)C=CC5=CC6=C(C=C52)OCO6",
        "image": "mol_58.svg",
        "sdf": "mol_58.sdf",
        "mw": 332.09,
        "logp": 3.43,
        "tpsa": 40.8,
        "hbd": 0,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts, roots and latex",
        "literature_note": "Sanguinarine predominant in roots; found throughout plant via latex (0.27\u20132.25% aerial; 3\u20134% roots)"
    },
    {
        "id": "59",
        "name": "Chelerythrine",
        "class": "Benzophenanthrine quaternary amine",
        "molecular_formula": "C21H17NO4",
        "referencias": "http://dx.doi.org/10.1016/j.chroma.2015.12.015",
        "smiles": "C[N+]1=C2C(=C3C=CC(=C(C3=C1)OC)OC)C=CC4=CC5=C(C=C42)OCO5",
        "image": "mol_59.svg",
        "sdf": "mol_59.sdf",
        "mw": 348.12,
        "logp": 3.72,
        "tpsa": 40.8,
        "hbd": 0,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts, roots and latex",
        "literature_note": "Chelerythrine in roots and aerial parts; concentrated in latex; prominent in roots"
    },
    {
        "id": "60",
        "name": "Dihydrochelerythrine",
        "class": "Dihydrobenzophen-anthridine",
        "molecular_formula": "C21H19NO4",
        "referencias": "https://doi.org/10.1016/j.arabjc.2022.104527",
        "smiles": "CN1CC2=C(C=CC(=C2OC)OC)C3=C1C4=CC5=C(C=C4C=C3)OCO5",
        "image": "mol_60.svg",
        "sdf": "mol_60.sdf",
        "mw": 349.13,
        "logp": 4.2,
        "tpsa": 40.16,
        "hbd": 0,
        "hba": 5,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts and roots",
        "literature_note": "Dihydrochelerythrine isolated from roots and aerial parts of C. majus"
    },
    {
        "id": "61",
        "name": "Dihydrosanguinarine",
        "class": "Dihydrobenzophen-anthridine",
        "molecular_formula": "C20H15NO4",
        "referencias": "https://doi.org/10.1016/j.arabjc.2022.104528",
        "smiles": "CN1CC2=C(C=CC3=C2OCO3)C4=C1C5=CC6=C(C=C5C=C4)OCO6",
        "image": "mol_61.svg",
        "sdf": "mol_61.sdf",
        "mw": 333.1,
        "logp": 3.91,
        "tpsa": 40.16,
        "hbd": 0,
        "hba": 5,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts and roots",
        "literature_note": "Dihydrosanguinarine predominates in roots (in vitro cultures, Zielinska et al., 2018)"
    },
    {
        "id": "62",
        "name": "Oxychelerythrine",
        "class": "Dihydrobenzophen-anthridine",
        "molecular_formula": "C21H17NO5",
        "referencias": "DOI: 10.1002/pca.2802",
        "smiles": "CN1C2=C(C=CC3=CC4=C(C=C32)OCO4)C5=C(C1=O)C(=C(C=C5)OC)OC",
        "image": "mol_62.svg",
        "sdf": "mol_62.sdf",
        "mw": 363.11,
        "logp": 3.59,
        "tpsa": 58.92,
        "hbd": 0,
        "hba": 6,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts and roots",
        "literature_note": "Oxychelerythrine from aerial parts and roots of C. majus"
    },
    {
        "id": "63",
        "name": "Norchelidonine",
        "class": "Hexahydrobenzophenthridine",
        "molecular_formula": "C19H17NO5",
        "referencias": "http://dx.doi.org/10.1016/j.chroma.2015.12.015",
        "smiles": "C1[C@H]([C@@H]2[C@H](C3=CC4=C(C=C31)OCO4)NCC5=C2C=CC6=C5OCO6)O",
        "image": "mol_63.svg",
        "sdf": "mol_63.sdf",
        "mw": 339.11,
        "logp": 1.99,
        "tpsa": 69.18,
        "hbd": 2,
        "hba": 6,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Whole plant (aerial parts and roots)",
        "literature_note": "Norchelidonine isolated from whole plant of C. majus (Kadan et al., 1992)"
    },
    {
        "id": "64",
        "name": "Oxysanguinarine",
        "class": "Dihydrobenzophen-anthridine",
        "molecular_formula": "C20H13NO5",
        "referencias": "Natural Product Communications Vol. 6 (11) 2011\u00a0",
        "smiles": "CN1C2=C(C=CC3=CC4=C(C=C32)OCO4)C5=C(C1=O)C6=C(C=C5)OCO6",
        "image": "mol_64.svg",
        "sdf": "mol_64.sdf",
        "mw": 347.08,
        "logp": 3.3,
        "tpsa": 58.92,
        "hbd": 0,
        "hba": 6,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts and roots",
        "literature_note": "Oxysanguinarine from aerial parts and roots of C. majus"
    },
    {
        "id": "65",
        "name": "Chelidonine",
        "class": "Hexahydrobenzophenthridine",
        "molecular_formula": "C20H19NO5",
        "referencias": "DOI 10.3389/fphar.2024.1440979",
        "smiles": "CN1CC2=C(C=CC3=C2OCO3)[C@@H]4[C@H]1C5=CC6=C(C=C5C[C@@H]4O)OCO6",
        "image": "mol_65.svg",
        "sdf": "mol_65.sdf",
        "mw": 353.13,
        "logp": 2.33,
        "tpsa": 60.39,
        "hbd": 1,
        "hba": 6,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts, roots and latex",
        "literature_note": "Chelidonine: major alkaloid in aerial parts and roots; latex 32x higher concentration than leaves"
    },
    {
        "id": "67",
        "name": "Chelamine",
        "class": "Hexahydrobenzophenthridine",
        "molecular_formula": "C20H19NO6",
        "referencias": "DOI: 10.1002/chem.200701775",
        "smiles": "CN1CC2=C(C=CC3=C2OCO3)[C@@H]4[C@H]1C5=CC6=C(C=C5[C@H]([C@@H]4O)O)OCO6",
        "image": "mol_67.svg",
        "sdf": "mol_67.sdf",
        "mw": 369.12,
        "logp": 1.82,
        "tpsa": 80.62,
        "hbd": 2,
        "hba": 7,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts",
        "literature_note": "Chelamine isolated from aerial parts of C. majus"
    },
    {
        "id": "68",
        "name": "Chelamidine",
        "class": "Hexahydrobenzophenthridine",
        "molecular_formula": "C21H23NO6",
        "referencias": "DOI: 10.1002/chem.200701776",
        "smiles": "CC(=O)N[C@H]1CCC2=CC(=C(C(=C2C3=CC=C(C(=O)C=C13)O)OC)OC)OC",
        "image": "mol_68.svg",
        "sdf": "mol_68.sdf",
        "mw": 385.15,
        "logp": 2.57,
        "tpsa": 94.09,
        "hbd": 2,
        "hba": 6,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts",
        "literature_note": "Chelamidine isolated from aerial parts of C. majus"
    },
    {
        "id": "69",
        "name": "(+)-Homochelidonine",
        "class": "Hexahydrobenzophenthridine",
        "molecular_formula": "C21H23NO5",
        "referencias": "http://dx.doi.org/10.1016/j.chroma.2015.12.015",
        "smiles": "CC(=O)O[C@H]1C=C[C@H]2[C@H]3CC4=C5[C@]2([C@H]1OC5=C(C=C4)OC(=O)C)CCN3C",
        "image": "mol_69.svg",
        "sdf": "mol_69.sdf",
        "mw": 369.16,
        "logp": 1.99,
        "tpsa": 65.07,
        "hbd": 0,
        "hba": 6,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts and roots",
        "literature_note": "(+)-Homochelidonine from aerial parts and roots of C. majus"
    },
    {
        "id": "70",
        "name": "Berberine",
        "class": "Protoberberine",
        "molecular_formula": "C20H17NO4",
        "referencias": "DOI 10.3389/fphar.2024.1440979",
        "smiles": "COC1=C(C2=C[N+]3=C(C=C2C=C1)C4=CC5=C(C=C4CC3)OCO5)OC",
        "image": "mol_70.svg",
        "sdf": "mol_70.sdf",
        "mw": 336.12,
        "logp": 3.1,
        "tpsa": 40.8,
        "hbd": 0,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts, roots and latex",
        "literature_note": "Berberine in aerial parts and roots; present in latex; widely distributed in whole plant"
    },
    {
        "id": "71",
        "name": "Berberrubine",
        "class": "Protoberberine",
        "molecular_formula": "C19H15NO4",
        "referencias": "https://doi.org/10.1016/j.jpba.2022.115199",
        "smiles": "COC1=C(C2=C[N+]3=C(C=C2C=C1)C4=CC5=C(C=C4CC3)OCO5)O",
        "image": "mol_71.svg",
        "sdf": "mol_71.sdf",
        "mw": 322.11,
        "logp": 2.79,
        "tpsa": 51.8,
        "hbd": 1,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts and roots",
        "literature_note": "Berberrubine from aerial parts and roots of C. majus"
    },
    {
        "id": "72",
        "name": "Corysamine",
        "class": "Protoberberine",
        "molecular_formula": "C20H15NO4",
        "referencias": "http://dx.doi.org/10.1016/j.phymed.2016.05.003",
        "smiles": "CC1=C2C=CC3=C(C2=C[N+]4=C1C5=CC6=C(C=C5CC4)OCO6)OCO3",
        "image": "mol_72.svg",
        "sdf": "mol_72.sdf",
        "mw": 334.11,
        "logp": 3.12,
        "tpsa": 40.8,
        "hbd": 0,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts and roots",
        "literature_note": "Corysamine from aerial parts and roots of C. majus"
    },
    {
        "id": "73",
        "name": "(S)-N-Methylstylopine",
        "class": "Protoberberine",
        "molecular_formula": "C20H19NO4",
        "referencias": "doi:10.1016/j.phytochem.2006.10.003",
        "smiles": "C[N@@+]12CCC3=CC4=C(C=C3[C@@H]1CC5=C(C2)C6=C(C=C5)OCO6)OCO4",
        "image": "mol_73.svg",
        "sdf": "mol_73.sdf",
        "mw": 338.14,
        "logp": 2.94,
        "tpsa": 36.92,
        "hbd": 0,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts",
        "literature_note": "N-Methylstylopine from aerial parts of C. majus"
    },
    {
        "id": "74",
        "name": "8-Oxycoptisine",
        "class": "Protoberberine",
        "molecular_formula": "C19H13NO5",
        "referencias": "https://doi.org/10.1016/j.arabjc.2022.104527",
        "smiles": "COC1=C(C2=C3C(=C1)C=CN=C3C(=O)C4=CC5=C(C=C42)OCO5)OC",
        "image": "mol_74.svg",
        "sdf": "mol_74.sdf",
        "mw": 335.08,
        "logp": 3.19,
        "tpsa": 66.88,
        "hbd": 0,
        "hba": 6,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts",
        "literature_note": "8-Oxycoptisine from aerial parts of C. majus"
    },
    {
        "id": "75",
        "name": "Stylopine",
        "class": "Protoberberine",
        "molecular_formula": "C19H17NO4",
        "referencias": "http://dx.doi.org/10.1016/j.chroma.2015.12.015",
        "smiles": "CC1(CO1)C2CC3=C(O2)C=C(C4=C3N(C5=CC=CC=C5C4=O)C)O",
        "image": "mol_75.svg",
        "sdf": "mol_75.sdf",
        "mw": 323.12,
        "logp": 2.49,
        "tpsa": 63.99,
        "hbd": 1,
        "hba": 5,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts (leaves) and roots",
        "literature_note": "Stylopine: major component of leaves of C. majus; also present in roots (Jang et al., 2004)"
    },
    {
        "id": "76",
        "name": "Coptisine",
        "class": "Protoberberine",
        "molecular_formula": "C19H13NO4",
        "referencias": "http://dx.doi.org/10.1016/j.phymed.2016.05.003",
        "smiles": "O1c3c(OC1)c2c[n+]6c(cc2cc3)c5cc4OCOc4cc5CC6",
        "image": "mol_76.svg",
        "sdf": "mol_76.sdf",
        "mw": 320.09,
        "logp": 2.81,
        "tpsa": 40.8,
        "hbd": 0,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts and roots",
        "literature_note": "Coptisine dominant in aerial shoots; also roots; high in latex; main alkaloid of herb (EMA)"
    },
    {
        "id": "77",
        "name": "Protopine",
        "class": "Protopine",
        "molecular_formula": "C20H19NO5",
        "referencias": "DOI 10.3389/fphar.2024.1440979",
        "smiles": "C1C[N+]2=C(C=C3C=CC4=C(C3=C2)OCO4)C5=CC6=C(C=C51)OCO6",
        "image": "mol_77.svg",
        "sdf": "mol_77.sdf",
        "mw": 320.09,
        "logp": 2.81,
        "tpsa": 40.8,
        "hbd": 0,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts and roots",
        "literature_note": "Protopine isolated from roots and aerial parts; isolated from celandine roots (Jusiak et al., 1989)"
    },
    {
        "id": "78",
        "name": "Cryptopine",
        "class": "Protopine",
        "molecular_formula": "C21H23NO5",
        "referencias": "http://dx.doi.org/10.1016/j.phymed.2016.05.003",
        "smiles": "CN1CCC2=CC(=C(C=C2C(=O)CC3=C(C1)C4=C(C=C3)OCO4)OC)OC",
        "image": "mol_78.svg",
        "sdf": "mol_78.sdf",
        "mw": 369.16,
        "logp": 2.85,
        "tpsa": 57.23,
        "hbd": 0,
        "hba": 6,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts and roots",
        "literature_note": "Cryptopine from aerial parts and roots of C. majus"
    },
    {
        "id": "79",
        "name": "Canadine",
        "class": "Aporphine",
        "molecular_formula": "C20H21NO4",
        "referencias": "https://doi.org/10.3390/ijms231810330\u00a0",
        "smiles": "COC1=C(C2=C(C[C@@H]3C4=CC5=C(C=C4CCN3C2)OCO5)C=C1)OC",
        "image": "mol_79.svg",
        "sdf": "mol_79.sdf",
        "mw": 339.15,
        "logp": 3.09,
        "tpsa": 40.16,
        "hbd": 0,
        "hba": 5,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts, roots and latex",
        "literature_note": "Canadine (tetrahydroberberine) in latex and whole plant of C. majus"
    },
    {
        "id": "80",
        "name": "Magnocurarine",
        "class": "Aporphine",
        "molecular_formula": "C19H23NO3",
        "referencias": "https://doi.org/10.1016/j.arabjc.2022.104527",
        "smiles": "CCOC1=CC=CC=C1OC(C2CNCCO2)C3=CC=CC=C3",
        "image": "mol_80.svg",
        "sdf": "mol_80.sdf",
        "mw": 313.17,
        "logp": 3.19,
        "tpsa": 39.72,
        "hbd": 1,
        "hba": 4,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts",
        "literature_note": "Magnocurarine from aerial parts of C. majus"
    },
    {
        "id": "81",
        "name": "Magnoflorine",
        "class": "Aporphine",
        "molecular_formula": "C20H23NO4",
        "referencias": "DOI 10.3389/fphar.2024.1440979",
        "smiles": "C1CC1CN2CC[C@]34[C@@H]5C(=O)CC[C@]3([C@H]2CC6=C4C(=C(C=C6)O)O5)O",
        "image": "mol_81.svg",
        "sdf": "mol_81.sdf",
        "mw": 341.16,
        "logp": 1.53,
        "tpsa": 70.0,
        "hbd": 2,
        "hba": 5,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts and roots",
        "literature_note": "Magnoflorine from aerial parts and roots of C. majus"
    },
    {
        "id": "82",
        "name": "Norchelidonine",
        "class": "Benzophenantridine alkaloids",
        "molecular_formula": "C19H17NO5",
        "referencias": "http://dx.doi.org/10.1016/j.chroma.2015.12.015",
        "smiles": "COC1=CC=C(C=C1)C2=C(ON=C2C3=CC=C(C=C3)OC)CC(=O)O",
        "image": "mol_82.svg",
        "sdf": "mol_82.sdf",
        "mw": 339.11,
        "logp": 3.65,
        "tpsa": 81.79,
        "hbd": 1,
        "hba": 5,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Whole plant (aerial parts and roots)",
        "literature_note": "Norchelidonine from whole plant of C. majus"
    },
    {
        "id": "83",
        "name": "Noroxyhydrastinine",
        "class": "Benzophenantridine alkaloids",
        "molecular_formula": "C10H9NO3",
        "referencias": "https://doi.org/10.1016/j.jpba.2022.115199",
        "smiles": "C1=CC2=C(C=C1O)C(=CN2)CC(=O)O",
        "image": "mol_83.svg",
        "sdf": "mol_83.sdf",
        "mw": 191.06,
        "logp": 1.5,
        "tpsa": 73.32,
        "hbd": 3,
        "hba": 2,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts",
        "literature_note": "Noroxyhydrastinine from aerial parts of C. majus"
    },
    {
        "id": "84",
        "name": "Indole-3-carboxaldehyde",
        "class": "Benzophenantridine alkaloids",
        "molecular_formula": "C9H7NO",
        "referencias": "DOI 10.3389/fphar.2024.1440979",
        "smiles": "C1=CC2=C(C(=C1)O)N=CC=C2",
        "image": "mol_84.svg",
        "sdf": "mol_84.sdf",
        "mw": 145.05,
        "logp": 1.94,
        "tpsa": 33.12,
        "hbd": 1,
        "hba": 2,
        "lipinski_pass": true,
        "ro5_violations": 0,
        "plant_part": "Aerial parts",
        "literature_note": "Indole-3-carboxaldehyde from aerial parts of C. majus"
    }
];